name: PHP Building Workflow

on:
  push:
    branches:
      - main

jobs:
  composer_install:
    runs-on: ubuntu-latest

    env:
      COMPOSER_VERSION: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composer_config
        uses: baschny/php-composer-action@v1
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          command: get_config

      - name: Cache composer downloads
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer_config.outputs.composer_cache_dir }}
          key: composer-v${{ steps.composer_config.outputs.composer_major_version }}

      - name: Run composer install
        uses: baschny/php-composer-action@v1
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          command: install

  phpunit_tests:
    runs-on: ubuntu-latest
    needs: composer_install

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set execute permissions for phpunit
        run: chmod +x vendor/bin/phpunit


      - name: Run PHPUnit setPuntajeHelperTest.php
        run: phpunit --configuration phpunit.xml tests/setPuntajeHelperTest.php

      - name: Run PHPUnit LoginHelperTest.php
        run: phpunit --configuration phpunit.xml tests/LoginHelperTest.php

      - name: Run PHPUnit getMateriasComTest.php
        run: phpunit --configuration phpunit.xml tests/getMateriasComTest.php

      - name: Run PHPUnit GreeterTest.php
        run: phpunit --configuration phpunit.xml tests/GreeterTest.php

      - name: Run PHPUnit tests for all files in tests folder
        run: phpunit tests

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml tests --testdox --coverage-text

      - name: Run PHPUnit tests and generate testdox report
        run: vendor/bin/phpunit --testdox

