name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install --no-dev --no-interaction --no-progress --no-suggest 
      - name: Create symbolic link for PHPUnit
        run: ln -s $(pwd)/vendor/bin/phpunit /usr/local/bin/phpunit
    
      - name: Run PHPUnit Tests
        run: composer test
